from django.shortcuts import render
"""Raivo added 2 sampleviews for UI.
Later it will be automatically generated by class FormView"""
def formView(request):
    return render(request, template_name='index.html')

def guideView(request):
    return render(request, template_name='guide.html')

