from django.shortcuts import render
from django.views.generic import FormView
from django.urls import reverse_lazy
from smarthub.forms import SmartAppForm
"""Raivo added 2 sampleviews for UI.
Later it will be automatically generated by class FormView"""
def formView(request):
    return render(request, template_name='index.html')

def guideView(request):
    return render(request, template_name='guide.html')

class SmartAppView(FormView):
    template_name = 'index.html'
    form_class = SmartAppForm
    success_url = reverse_lazy('guide')

    def form_valid(self, form):
        form_data = form.cleaned_data
        for k, v in form_data.items():
            print(f"{k}: {v}")


        return super().form_valid(form)
